export const visualTokens = {
  darkModeStrategy: 'class',
  visualDialect: 'fauvist-control-plane',
  colors: {
    primary: '#1E3AFF',
    secondary: '#07111F',
    accent: '#FF3D18',
    lightBackground: '#FDFFF1',
    lightSurface: '#FFFDF5',
    lightSurfaceMuted: '#EAF3D1',
    border: '#07111F',
    textStrong: '#07111F',
    textMuted: '#35405A',
    darkBackground: '#07111F',
    darkSurface: '#101827',
    surface: '#FFFDF5',
    terminal: '#07111F'
  },
  fontFamilySans:
    'Geist, Cabinet Grotesk, Satoshi, Outfit, Inter, -apple-system, BlinkMacSystemFont, SF Pro Text, Segoe UI, sans-serif'
} as const;

export const visualClassNames = [
  'bg-env',
  'bg-grid',
  'app-container',
  'app-ready',
  'ou-shell',
  'ou-shell-backdrop',
  'ou-shell-grid',
  'ou-surface',
  'ou-surface-muted',
  'ou-card',
  'ou-card-strong',
  'ou-page-enter',
  'ou-card-enter',
  'ou-fade-in',
  'ou-stagger-1',
  'ou-stagger-2',
  'ou-stagger-3',
  'ou-stagger-4',
  'ou-skeleton',
  'ou-scroll-glow',
  'island-panel',
  'island-card',
  'btn-glow',
  'ou-input',
  'ou-toggle',
  'ou-panel',
  'ou-select',
  'glass-input',
  'glass-toggle',
  'logo-cat',
  'page-view',
  'active',
  'stagger-1',
  'stagger-2',
  'svg-flow-stop-1',
  'svg-flow-stop-2',
  'svg-line-dash',
  'nav-item',
  'nav-active',
  'overlay',
  'open',
  'drawer-panel',
  'modal-panel',
  'status-dot',
  'status-idle',
  'status-online'
] as const;
