export const visualTokens = {
  darkModeStrategy: 'class',
  colors: {
    primary: '#2563EB',
    secondary: '#F97316',
    accent: '#F97316',
    lightBackground: '#f8fafc',
    lightSurface: '#ffffff',
    lightSurfaceMuted: '#f1f5f9',
    border: '#e2e8f0',
    textStrong: '#0f172a',
    textMuted: '#475569',
    darkBackground: '#07111f',
    darkSurface: '#0b1323',
    surface: '#ffffff',
    terminal: '#0f172a'
  },
  fontFamilySans:
    'Geist, Cabinet Grotesk, Satoshi, Outfit, Inter, -apple-system, BlinkMacSystemFont, SF Pro Text, Segoe UI, sans-serif'
} as const;

export const visualClassNames = [
  'bg-env',
  'bg-grid',
  'app-container',
  'app-ready',
  'ou-shell',
  'ou-shell-backdrop',
  'ou-shell-grid',
  'ou-shell-ribbon',
  'ou-surface',
  'ou-surface-muted',
  'ou-card',
  'ou-card-strong',
  'ou-page-enter',
  'ou-card-enter',
  'ou-fade-in',
  'ou-stagger-1',
  'ou-stagger-2',
  'ou-stagger-3',
  'ou-stagger-4',
  'ou-skeleton',
  'ou-scroll-glow',
  'island-panel',
  'island-card',
  'btn-glow',
  'ou-input',
  'ou-toggle',
  'ou-panel',
  'ou-select',
  'glass-input',
  'glass-toggle',
  'logo-cat',
  'page-view',
  'active',
  'stagger-1',
  'stagger-2',
  'svg-flow-stop-1',
  'svg-flow-stop-2',
  'svg-line-dash',
  'nav-item',
  'nav-active',
  'overlay',
  'open',
  'drawer-panel',
  'modal-panel',
  'status-dot',
  'status-idle',
  'status-online'
] as const;
