import type { SubscriptionClientIdentity, XrayInbound } from '../../domain';
import { renderPublicSubscriptionOutput } from './subscription-output';

const inbound: XrayInbound = {
  id: 'inbound-real-vless-2443',
  nodeId: 'node-real-hkg',
  agentId: 'agent-real-hkg',
  customerName: 'Acme',
  serverAddress: 'edge.example.com',
  clientIdentity: '11111111-1111-4111-8111-111111111111',
  subscriptionRule: 'premium',
  protocol: 'vless',
  label: 'Acme HK VLESS',
  listenAddress: '0.0.0.0',
  listenPort: 2443,
  status: 'enabled',
  clients: [
    {
      id: '11111111-1111-4111-8111-111111111111',
      email: 'acme@example.com',
      enabled: true,
      credentialType: 'uuid',
      flow: 'xtls-rprx-vision',
      trafficLimitBytes: 500 * 1024 * 1024 * 1024,
      usedTrafficBytes: 12 * 1024 * 1024 * 1024,
      expiresAt: '2027-12-31T23:59:59.000Z',
      ipLimit: 3
    }
  ],
  streamSettings: {
    network: 'tcp',
    security: 'reality',
    sni: 'edge.example.com',
    fingerprint: 'chrome'
  },
  tls: {
    enabled: true,
    certificateId: 'cert-edge',
    alpn: ['h2', 'http/1.1']
  },
  reality: {
    enabled: true,
    publicKey: 'reality-public-key',
    fingerprint: 'chrome',
    shortIds: ['a1b2c3d4'],
    serverNames: ['edge.example.com']
  },
  fallbacks: [],
  sniffingEnabled: true,
  configVersion: 'cfg-real-vless-2443'
};

const client: SubscriptionClientIdentity = {
  id: 'sub-client-acme',
  customerName: 'Acme',
  displayName: 'Acme Premium',
  subId: 'sub_acme_premium',
  email: 'acme@example.com',
  enabled: true,
  protocol: 'vless',
  group: 'premium',
  trafficLimitBytes: 500 * 1024 * 1024 * 1024,
  usedTrafficBytes: 12 * 1024 * 1024 * 1024,
  expiresAt: '2027-12-31T23:59:59.000Z',
  ipLimit: 3,
  sourceIds: [],
  selectedTags: ['premium'],
  includeFilter: '',
  excludeFilter: '',
  regionFilter: [],
  routingRule: 'tag:premium',
  maxLatencyMs: 0,
  sortStrategy: 'latency',
  formats: ['plain', 'clash', 'sing-box'],
  outputFormats: ['uri', 'clash', 'sing-box'],
  templateName: 'mihomo-compatible.yaml',
  accessTokenPreview: 'ou_acme...mium',
  securePathPreview: '/x7K2mP9vL4qR1wDz',
  generatedNodeCount: 1
};

describe('subscription-output', () => {
  it('renders real URI links from Xray inbound clients', () => {
    const output = renderPublicSubscriptionOutput({
      client,
      format: 'uri',
      inbounds: [inbound]
    });

    expect(output.contentType).toBe('text/plain; charset=utf-8');
    expect(output.body).toContain('vless://11111111-1111-4111-8111-111111111111@edge.example.com:2443');
    expect(output.body).toContain('security=reality');
    expect(output.body).toContain('#Acme+HK+VLESS');
    expect(output.headers['subscription-userinfo']).toContain(`total=${500 * 1024 * 1024 * 1024}`);
    expect(output.nodeCount).toBe(1);
  });

  it('renders Clash/Mihomo and sing-box configs without placeholder nodes', () => {
    const clash = renderPublicSubscriptionOutput({
      client,
      format: 'mihomo',
      inbounds: [inbound]
    });
    const singBox = renderPublicSubscriptionOutput({
      client,
      format: 'sing-box',
      inbounds: [inbound]
    });

    expect(clash.body).toContain('mihomo-compatible subscription generated by OU-UI Next');
    expect(clash.body).toContain('Acme HK VLESS');
    expect(clash.body).toContain('edge.example.com');
    expect(clash.body).not.toContain('203.0.');

    expect(JSON.parse(singBox.body)).toMatchObject({
      outbounds: [
        expect.objectContaining({
          type: 'vless',
          tag: 'Acme HK VLESS',
          server: 'edge.example.com',
          server_port: 2443
        }),
        expect.objectContaining({
          type: 'direct'
        })
      ]
    });
  });

  it('uses the normalized client UUID instead of the customer label in VLESS subscription URIs', () => {
    const normalizedInbound: XrayInbound = {
      ...inbound,
      clientIdentity: 'acme-human-label',
      clients: [
        {
          ...inbound.clients[0],
          id: '22222222-2222-4222-8222-222222222222'
        }
      ]
    };
    const output = renderPublicSubscriptionOutput({
      client,
      format: 'uri',
      inbounds: [normalizedInbound]
    });

    expect(output.body).toContain('vless://22222222-2222-4222-8222-222222222222@edge.example.com:2443');
    expect(output.body).not.toContain('vless://acme-human-label@edge.example.com:2443');
  });
});
